config/routes.rb
Ethioboston::Application.routes.draw do
  devise_for :users

  devise_scope :user do 
    get '/users/sign_out' => 'devise/sessions#destroy'
    post '/users/sign_up' => 'devise/registrations#new'
  end

  resources :users do 
    resources :call_lists, only: [:new, :create]
  end

  get '/dashboards' => 'dashboards#index', as: :user_root
 
   root 'welcome#index'

  resources :housings, only: [ :index, :show, :new, :create, :edit, :update ]
  resources :jobs, only: [ :index, :show, :new, :create, :edit , :update]
  resources :dashboards, only: [ :index ]
  resources :welcome, only: [ :index ]

  post 'twilio/text' => 'twilio#vtext'
  post '/jobs/new' => 'jobs#new'
  post '/housings/new' => 'housings#new'
  get "/users/:user_id/call_lists" => 'call_lists#new'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/call_list.rb
class CallList < ActiveRecord::Base
  validates :user, presence: true 
  validates :phone_number, presence: true, numericality: true
  validates :reason, presence: true, inclusion: { in: %w(Homes Jobs Both) }

  belongs_to :user
end

app/models/housing.rb
class Housing < ActiveRecord::Base
  

  validates :type_of_housing, presence: true, length: { maximum: 140 }
  validates :city, presence: true, format: { with: /\A[a-zA-Z]+\z/ }
  validates :state, presence: true, format: { with: /\A[a-zA-Z]+\z/ }
  validates :price, presence: true, length: { maximum: 5 }, numericality: { only_integer: true }
  validates :contact_number, presence: true, length: { minimum: 10, maximum: 10 }, numericality: { only_integer: true }
  validates :contact_email, presence: true, format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ }

  belongs_to :user
  
  mount_uploader :avatar, AvatarUploader

  paginates_per 5
end

app/models/job.rb
class Job < ActiveRecord::Base
  
  validates :name, presence: true
  validates :email, presence: true, format: {with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ }
  validates :job_title, presence: true
  validates :location, presence: true
  validates :description, presence: true, length: { maximum: 400}
  validates :contact_phone_number, presence: true, length: { minimum: 10, maximum: 10 }, numericality: { only_integer: true }

  belongs_to :user

  paginates_per 5

  mount_uploader :avatar, AvatarUploader
end

app/models/message.rb
class Message
  def initialize
    @client = Twilio::REST::Client.new(ENV['TWILIO_SID'], ENV['TWILIO_AUTH_TOKEN'])
  end

  def send_text(to, body)
    @client.account.messages.create({
      from: ENV['TWILIO_NUMBER'],
      to: to,
      body: body
    })
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs
  has_many :housings
  has_one :call_list

  def register
    if save 
      Notification.receipt(self).deliver
      return true
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!, except: [:new, :create, :edit, 'welcome#index' ]
end

app/controllers/call_lists_controller.rb
class CallListsController < ApplicationController
  before_action :authenticate_user!
  def new
    @user = current_user
    @call_list = CallList.new
  end
  def create
    @call_list = CallList.new(call_params)
    if @call_list.save
      redirect_to user_root_path
      flash[:notice] = "Thank You"
    else
      flash[:notice] = "DIDNT WORK"
      redirect_to user_root_path   
    end
  end

  private

  def call_params
    params.require(:call_list).permit(:phone_number, :reason).merge(user: current_user)
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  def index
    @housings = Housing.order(created_at: :desc).page params[:page]
    @jobs = Job.order(created_at: :desc).page params[:page]
    @user = current_user
    @call_list = CallList.new
  end
end

app/controllers/housings_controller.rb
class HousingsController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create, :edit]

  def show
    @housing = Housing.find(params[:id])
  end

  def new
    @housing = Housing.new
  end

  def create
    @housing = Housing.create(housing_params)

    if @housing.save && verify_recaptcha
      HousingNotifierWorker.perform_async(@housing.id)
      redirect_to new_housing_path, notice: 'Thank You for Sending Us Rental Information'
    else 
      render :new
    end
  end

  def edit
    @housing = Housing.find(params[:id])
  end

  def update
    @housing = Housing.find(params[:id])
    if @housing.update(housing.params)
      redirect_to new_housing_path
    else
      render :new
    end
  end

  private

  def housing_params
    params.require(:housing).permit(:type_of_housing, :city, :state, :price, :availability_date, :contact_number, :contact_email, :avatar)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create, :edit]

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.create(job_params)
    
    if @job.save && verify_recaptcha
      JobsNotifierWorker.perform_async(@job.id)
      redirect_to new_job_path, notice: 'Thank You for Sending Us Job Opening Information.'
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to new_housing_path
    else 
      render :edit
    end
  end

  private

  def job_params
    params.require(:job).permit(:name, :email, :job_title, :location, :description, :contact_phone_number, :avatar)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/index.html.erb
<div class="row">

  <div class="small-6 large-6 columns">
    <h1> HOUSE LISTINGS </h1>
    <ul>
      <% @housings.each do |housing| %>
          <li><%= link_to "#{housing.type_of_housing}, #{housing.city} #{housing.state}", housing_path(housing) %></li>
          <% end %>
    </ul>
      <%= paginate @housings, :remote => true %>
  </div>

  <div class="small-6 large-6 columns">
    <h1> JOB LISTINGS </h1>
    <ul>
      <% @jobs.each do |job| %>
      <li><%= link_to "#{job.job_title}, #{job.location}", job_path(job) %></li>
      <% end %>
    </ul>
    <%= paginate @jobs, :remote => true %>
  </div >
</div>
  <div class='small-8 columns'>
    <%= simple_form_for [@user, @call_list], remote: true do |f| %>
      <%= f.input :phone_number, placeholder: '6175555555' %>
      <%= f.input :reason, collection: [ 'Homes', 'Jobs', 'Both'] %>
      <%= f.button :submit, class: "sign-up-button" %>
      <% end %>
  </div>

app/views/housings/_form.html.erb
<%= simple_form_for(@housing) do |f| %>

  <% if @housing.errors.full_messages.count > 0 %>
    <ul>
      <% @housing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row">
    <div class="large-5 coumns">
      <div>
        <%= f.input :type_of_housing, placeholder: "type of housing" %>
      </div>
      <div>
        <%= f.input :city, placeholder: "city" %>
      </div>
      <div>
        <%= f.input :state, placeholder: "state" %>
      </div>
      <div>
        <%= f.input :price, placeholder: "price" %>
      </div>
      <div>
        <%= f.input :availability_date, placeholder: "availability date" %>
      </div>
      <div>
        <%= f.input :contact_number, placeholder: "contact number" %>
      </div>
      <div>
        <%= f.input :contact_email, placeholder: "contact email" %>
      </div>
      <div>
        <%= f.file_field :avatar %>
      </div>
      <div>
         <%= recaptcha_tags ajax: true %>
      </dv>  
      <div>
        <%= f.button :submit, class: 'sign-up-button' %>
      </div>
    </div>
  </div>
<% end %>

app/views/housings/edit.html.erb
<%= render 'housings/new' %>

app/views/housings/new.html.erb
<%= render 'form' %>

app/views/housings/show.html.erb
<ul>
  <%= @housing.type_of_housing %><br>
  <%= @housing.city %><br>
  <%= @housing.state %><br>
  <%= @housing.price %><br>
  <%= @housing.availability_date %><br>
  <%= @housing.contact_number %><br>
  <%= @housing.contact_email %><br>
  <%= image_tag @housing.avatar %><br>
</ul>

app/views/jobs/_form.html.erb
<%= simple_form_for(@job) do |f| %>

  <% if @job.errors.full_messages.count > 0 %>
    <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row">
    <div class="large-5 coumns">
      <div>
        <%= f.input :name, placeholder: "name" %>
      </div>
      <div>
        <%= f.input :email, placeholder: "email" %>
      </div>
      <div>
        <%= f.input :job_title, placeholder: "job title" %>
      </div>
      <div>
        <%= f.input :location, placeholder: "location" %>
      </div>
      <div>
        <%= f.input :description, placeholder: "description" %>
      </div>
      <div>
        <%= f.input :contact_phone_number, placeholder: "contact phone number" %>
      </div>
      <div>
          <%= f.file_field :avatar %>
      </div>
      <div>
        <%= recaptcha_tags ajax: true %>  
      </div>
      <div>
        <%= f.button :submit, class: 'sign-up-button' %>
      </div>
     </div>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<%= render 'jobs/new' %>

app/views/jobs/new.html.erb
<%= render 'form' %>

app/views/jobs/show.html.erb
  <ul>
    <%= @job.job_title %><br>
    <%= @job.email %> <br>
    <%= @job.location %><br>
    <%= @job.description %><br>
    <%= @job.contact_phone_number %> <br>
    <%= image_tag @job.avatar %><br>
  </ul>   

app/views/layouts/_navbar.html.erb
<div class="sticky">
  <nav class="top-bar" data-topbar>

    <ul class="title-area">
      <li class="name">
        <h1><a href="/">BOSTON-ETHIOPIANS INC.</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <% if user_signed_in? %>
          <li class="active"><%= current_user.email %></li>
          <li class="active"><%= link_to "SIGN OUT", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li class="active"><%= link_to "SIGN UP", new_user_registration_path%></li>
          <li class="active"><%= link_to "SIGN IN", new_user_session_path %></li>
        <%end%>
      </ul>
    </section>

  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : 'EthioBoston' %></title>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag    "application" %>

    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Keania+One' rel='stylesheet' type='text/css'>


  </head>

  <body>
    <%= render 'layouts/navbar' %>

     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>

    <div class="row">
      <div class="small-12 columns">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/notification/new_house.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>New House Listing Posted.</p>
  </body>
</html>

app/views/notification/new_house.text.erb
New House Listing Posted.

app/views/notification/new_job.text.erb
New Job Listed!
  

app/views/notification/receipt.text.erb
Welcome to www.ethioboston.herokuapp.com
    
Thanks for joining and have a great day!

app/views/notification/update.text.erb
New Posting. 

app/views/welcome/index.html.erb
<br>
</br>
<br>
</br>
<br>
</br>
<br>
</br>
<br>
</br>
<br>
</br>
<br>
</br>
<br>
</br>
<div class="row">
  <div class="small-4 columns">
    <%= link_to 'SIGN UP',new_user_registration_path, class: 'button expand' %> 
  </div>
  <div class="small-4 columns">
     <%= link_to 'POST JOBS', new_job_path, class: 'button expand' %>
  </div>
  <div class="small-4 columns">
     <%= link_to 'POST HOUSINGS', new_housing_path, class: 'button expand' %>
  </div>
</div>